name: ispect_example
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: any
  flutter_localizations:
    sdk: flutter
  ispect:
    path: ../

  talker_flutter: ^4.4.0
  dio: ^5.5.0
  flutter_riverpod: ^2.5.1
  talker_riverpod_logger: ^4.4.0
  talker_dio_logger: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

flutter_gen:
  output: lib/src/core/assets/generated
  line_length: 120

flutter_intl:
  enabled: true
  class_name: AppGeneratedLocalization
  main_locale: en
  arb_dir: lib/src/core/localization/translations
  output_dir: lib/src/core/localization/generated
