name: ispect
description: "A package combining Inspector, Talker, and more from pub.dev for efficient project implementation."
version: 1.6.8
homepage: https://github.com/K1yoshiSho/ispect.git
issue_tracker: https://github.com/K1yoshiSho/ispect/issues

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: any
  flutter_localizations:
    sdk: flutter

    # Logging
  talker_flutter: ^4.3.4
  talker_dio_logger: ^4.3.4
  talker_bloc_logger: ^4.3.4
  talker_riverpod_logger: ^1.1.4

  # Utils
  path_provider: ^2.1.3
  share_plus: ^9.0.0
  package_info_plus: ^8.0.0
  device_info_plus: ^10.1.0

  # UI
  gap: ^3.0.1
  auto_size_text: ^3.0.0
  feedback_plus: ^0.1.3

  # Lints
  custom_lint: ^0.6.4

  # Others
  provider: ^6.1.2
  dio: ^5.5.0
  flutter_bloc: ^8.1.6
  simple_app_cache_manager: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  pyramid_lint: ^2.0.0

flutter:
  generate: true
