name: ispect
description: "A package combining Inspector, Talker, and more from pub.dev for efficient project implementation."
version: 1.9.4-beta.10
homepage: https://github.com/K1yoshiSho/ispect.git
issue_tracker: https://github.com/K1yoshiSho/ispect/issues

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: any
  flutter_localizations:
    sdk: flutter

  meta:
    any

    # Logging
  talker_flutter: ^4.4.1
  talker_dio_logger: ^4.4.1
  talker_bloc_logger: ^4.4.1
  talker_riverpod_logger: ^4.4.1

  # Utils
  path_provider: ^2.1.4
  share_plus: ^10.0.1
  package_info_plus: ^8.0.2
  device_info_plus: ^10.1.2
  atlassian_apis: ^0.15.0
  file_picker: ^8.0.7

  # UI
  gap: ^3.0.1
  auto_size_text: ^3.0.0
  font_awesome_flutter: ^10.7.0
  flutter_markdown: ^0.7.4+1

  # Lints
  # custom_lint: ^0.6.4

  # Others
  provider: ^6.1.2
  dio: ^5.5.0
  flutter_bloc: ^8.1.6
  google_generative_ai: ^0.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  # pyramid_lint: ^2.0.0

flutter:
  generate: true
  assets:
    - assets/icons/
    - assets/lottie/
