name: ispect_jira
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  atlassian_apis: ^0.15.0
  ispect:
    path: ../ispect
  flutter_bloc: ^8.1.6
  meta: ^1.15.0
  gap: ^3.0.1
  file_picker: ^8.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
